image: python:3.12

before_script:
  - pip install tox

tests:
  parallel:
    matrix:
      - TOX-TEST-ENV: py38
        PYTHON_VERSION: "3.8"
      - TOX-TEST-ENV: py39
        PYTHON_VERSION: "3.9"
      - TOX-TEST-ENV: py310
        PYTHON_VERSION: "3.10"
      - TOX-TEST-ENV: py311
        PYTHON_VERSION: "3.11"
      - TOX-TEST-ENV: py312
        PYTHON_VERSION: "3.12"
    image: python:$PYTHON_VERSION
    script:
      - tox -e $TOX-TEST-ENV

lint:
  script:
    - tox -e lint

type-check:
  script:
    - tox -e type-check

format:
  script:
    - tox -e format

coverage:
  before_script: []
  script:
    - pip install pytest pytest-cov coverage
    - coverage erase
    - pytest -q
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
