name: Upload coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate and upload coverage
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tests with tox
      run: tox -e py311
    - name: Generate coverage report
      run: coverage xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
